export type Category = "women" | "men" | "lgbtq" | "couples";

export interface Product {
  id: string;
  name: string;
  slug: string;
  category: Category;
  tags: string[];
  price: number;
  originalPrice?: number;
  isSale: boolean;
  isNew: boolean;
  isBestseller: boolean;
  rating: number;
  reviewCount: number;
  description: string;
  features: string[];
  gradient: string;
}

export const products: Product[] = [
  {
    id: "1",
    name: "Rose Quartz Wand",
    slug: "rose-quartz-wand",
    category: "women",
    tags: ["vibrator", "women", "bestseller"],
    price: 49.99,
    isSale: false,
    isNew: false,
    isBestseller: true,
    rating: 4.8,
    reviewCount: 312,
    description:
      "A beautifully crafted body-safe silicone wand with 10 powerful vibration patterns and whisper-quiet motor. Rechargeable via USB-C.",
    features: ["Body-safe silicone", "Whisper-quiet motor", "Waterproof IPX7", "USB-C charging", "10 vibration modes"],
    gradient: "from-pink-200 to-rose-300",
  },
  {
    id: "2",
    name: "Velvet Luxe Set",
    slug: "velvet-luxe-set",
    category: "women",
    tags: ["set", "women", "gift"],
    price: 89.99,
    originalPrice: 119.99,
    isSale: true,
    isNew: false,
    isBestseller: false,
    rating: 4.7,
    reviewCount: 187,
    description:
      "Everything you need in one elegant gift box. Includes a dual-stimulation vibrator and premium water-based lubricant.",
    features: ["2-piece set", "Gift box included", "Body-safe silicone", "Fragrance-free lube", "Rechargeable"],
    gradient: "from-purple-200 to-pink-300",
  },
  {
    id: "3",
    name: "Luna Suction Pro",
    slug: "luna-suction-pro",
    category: "women",
    tags: ["suction", "women", "bestseller"],
    price: 64.99,
    isSale: false,
    isNew: true,
    isBestseller: true,
    rating: 4.9,
    reviewCount: 521,
    description:
      "Innovative air-pulse technology delivers intense, touch-free stimulation. 11 suction intensities, premium silicone.",
    features: ["Air-pulse technology", "11 intensities", "Waterproof", "USB magnetic charge", "Compact design"],
    gradient: "from-violet-200 to-purple-300",
  },
  {
    id: "4",
    name: "Noir Rabbit Classic",
    slug: "noir-rabbit-classic",
    category: "women",
    tags: ["rabbit", "women", "dual"],
    price: 74.99,
    originalPrice: 94.99,
    isSale: true,
    isNew: false,
    isBestseller: false,
    rating: 4.6,
    reviewCount: 243,
    description:
      "Iconic dual-stimulation design with flexible arm. 12 combined vibration patterns for internal and external pleasure.",
    features: ["Dual stimulation", "Flexible arm", "12 patterns", "Body-safe silicone", "Waterproof"],
    gradient: "from-gray-800 to-gray-900",
  },
  {
    id: "5",
    name: "Obsidian Ring Pro",
    slug: "obsidian-ring-pro",
    category: "men",
    tags: ["ring", "men", "couples"],
    price: 34.99,
    isSale: false,
    isNew: false,
    isBestseller: true,
    rating: 4.5,
    reviewCount: 198,
    description:
      "Vibrating silicone ring for enhanced pleasure. Stretchy, body-safe, and waterproof. One-touch controls.",
    features: ["Stretchy silicone", "One-touch control", "Waterproof", "USB-C charging", "Body-safe"],
    gradient: "from-gray-700 to-slate-800",
  },
  {
    id: "6",
    name: "Storm Stroker",
    slug: "storm-stroker",
    category: "men",
    tags: ["stroker", "men"],
    price: 54.99,
    isSale: false,
    isNew: true,
    isBestseller: false,
    rating: 4.7,
    reviewCount: 134,
    description:
      "Ultra-realistic textured sleeve in premium TPE material. Discreet travel case included.",
    features: ["Premium TPE", "Textured interior", "Travel case included", "Easy to clean", "Discreet design"],
    gradient: "from-blue-900 to-indigo-900",
  },
  {
    id: "7",
    name: "Apex P-Wand",
    slug: "apex-p-wand",
    category: "men",
    tags: ["prostate", "men", "wand"],
    price: 69.99,
    originalPrice: 89.99,
    isSale: true,
    isNew: false,
    isBestseller: false,
    rating: 4.8,
    reviewCount: 167,
    description:
      "Ergonomically curved prostate massager with dual vibration motors. Hits the P-spot precisely every time.",
    features: ["Dual motors", "Ergonomic curve", "10 patterns", "Waterproof IPX7", "Magnetic charge"],
    gradient: "from-indigo-700 to-purple-800",
  },
  {
    id: "8",
    name: "Pride Harness Kit",
    slug: "pride-harness-kit",
    category: "lgbtq",
    tags: ["harness", "lgbtq", "strap-on"],
    price: 84.99,
    isSale: false,
    isNew: false,
    isBestseller: true,
    rating: 4.9,
    reviewCount: 289,
    description:
      "Fully adjustable vegan leather harness compatible with any O-ring dildo. Comes with a premium silicone dildo.",
    features: ["Vegan leather", "Fully adjustable", "Universal O-ring", "Silicone dildo included", "Inclusive sizing"],
    gradient: "from-red-400 via-yellow-300 to-pink-400",
  },
  {
    id: "9",
    name: "Rainbow Plug Set",
    slug: "rainbow-plug-set",
    category: "lgbtq",
    tags: ["plug", "lgbtq", "set", "anal"],
    price: 44.99,
    isSale: false,
    isNew: true,
    isBestseller: false,
    rating: 4.7,
    reviewCount: 201,
    description:
      "Three graduated plugs in body-safe silicone with vibrant rainbow jewel bases. Perfect for beginners to advanced.",
    features: ["3-piece set", "Graduated sizes", "Body-safe silicone", "Jewel base", "Easy clean"],
    gradient: "from-pink-400 via-purple-400 to-blue-400",
  },
  {
    id: "10",
    name: "Duo Wave Couples Vibe",
    slug: "duo-wave-couples-vibe",
    category: "couples",
    tags: ["couples", "wearable", "vibrator"],
    price: 79.99,
    originalPrice: 99.99,
    isSale: true,
    isNew: false,
    isBestseller: true,
    rating: 4.8,
    reviewCount: 378,
    description:
      "Wearable vibrator for couples. Hands-free, app-controlled, with 10 vibration patterns. Stays in place.",
    features: ["App-controlled", "Wearable", "Hands-free", "10 patterns", "Whisper-quiet"],
    gradient: "from-rose-300 to-violet-300",
  },
  {
    id: "11",
    name: "Sensory Blindfold & Cuff Set",
    slug: "sensory-blindfold-cuff-set",
    category: "couples",
    tags: ["couples", "bondage", "set"],
    price: 39.99,
    isSale: false,
    isNew: false,
    isBestseller: false,
    rating: 4.6,
    reviewCount: 154,
    description:
      "Velvet blindfold and adjustable wrist cuffs for beginners exploring sensory play. Safe and comfortable.",
    features: ["Soft velvet", "Adjustable cuffs", "Quick-release", "Beginner-friendly", "Gift box"],
    gradient: "from-gray-800 to-rose-900",
  },
  {
    id: "12",
    name: "Glow Dildo — Crystal Clear",
    slug: "glow-dildo-crystal-clear",
    category: "lgbtq",
    tags: ["dildo", "lgbtq", "glass-alternative"],
    price: 59.99,
    isSale: false,
    isNew: true,
    isBestseller: false,
    rating: 4.7,
    reviewCount: 112,
    description:
      "Borosilicate-quality body-safe silicone dildo with realistic texture. Temperature-play compatible. Harness-compatible.",
    features: ["Temperature play", "Harness-compatible", "Body-safe silicone", "Realistic texture", "Easy clean"],
    gradient: "from-cyan-200 to-teal-300",
  },
  {
    id: "13",
    name: "Petal Clitoral Brush",
    slug: "petal-clitoral-brush",
    category: "women",
    tags: ["women", "clitoral", "whisper-quiet"],
    price: 42.99,
    isSale: false,
    isNew: false,
    isBestseller: false,
    rating: 4.5,
    reviewCount: 97,
    description:
      "Ultra-soft brush tip with 7 whisper-quiet vibration settings. Perfect for sensitive stimulation.",
    features: ["Soft brush tip", "7 settings", "Whisper-quiet", "Waterproof", "USB-C charge"],
    gradient: "from-pink-100 to-rose-200",
  },
  {
    id: "14",
    name: "Men's Delay Spray",
    slug: "mens-delay-spray",
    category: "men",
    tags: ["men", "spray", "wellness"],
    price: 19.99,
    isSale: false,
    isNew: false,
    isBestseller: false,
    rating: 4.4,
    reviewCount: 203,
    description:
      "Water-based, condom-compatible desensitising spray. Dermatologist tested, absorbed in 10 minutes.",
    features: ["Water-based", "Condom-compatible", "Dermatologist tested", "Fast-absorbing", "60 sprays"],
    gradient: "from-slate-600 to-slate-700",
  },
  {
    id: "15",
    name: "The Intimacy Card Game",
    slug: "intimacy-card-game",
    category: "couples",
    tags: ["couples", "game", "connection"],
    price: 24.99,
    isSale: false,
    isNew: true,
    isBestseller: false,
    rating: 4.9,
    reviewCount: 445,
    description:
      "150 intimacy-building conversation and challenge cards. Perfect for date nights. Inclusive and shame-free.",
    features: ["150 cards", "Inclusive", "All relationship types", "Gift-ready box", "Conversation starters"],
    gradient: "from-amber-200 to-rose-200",
  },
  {
    id: "16",
    name: "Silicone Lube — 200ml",
    slug: "silicone-lube-200ml",
    category: "couples",
    tags: ["lube", "couples", "essential"],
    price: 16.99,
    originalPrice: 21.99,
    isSale: true,
    isNew: false,
    isBestseller: true,
    rating: 4.8,
    reviewCount: 589,
    description:
      "Long-lasting, ultra-smooth silicone lubricant. A little goes a long way. Not compatible with silicone toys.",
    features: ["Long-lasting", "Condom-compatible", "Fragrance-free", "Dermatologist tested", "200ml pump bottle"],
    gradient: "from-sky-200 to-blue-200",
  },
  {
    id: "17",
    name: "Arch G-Spot Vibe",
    slug: "arch-g-spot-vibe",
    category: "women",
    tags: ["women", "g-spot", "vibrator"],
    price: 55.99,
    isSale: false,
    isNew: false,
    isBestseller: true,
    rating: 4.8,
    reviewCount: 267,
    description:
      "Precisely curved G-spot vibrator with rumbly deep motor. Flared base for safe use. 8 vibration modes.",
    features: ["G-spot curve", "Deep rumbly motor", "8 modes", "Waterproof", "Body-safe silicone"],
    gradient: "from-fuchsia-200 to-pink-300",
  },
  {
    id: "18",
    name: "Trans Pride Packers — Set of 3",
    slug: "trans-pride-packers",
    category: "lgbtq",
    tags: ["lgbtq", "packer", "trans"],
    price: 49.99,
    isSale: false,
    isNew: false,
    isBestseller: false,
    rating: 4.9,
    reviewCount: 178,
    description:
      "Ultra-realistic soft-pack packers in three skin-tone options. Lightweight, skin-safe silicone blend.",
    features: ["3 skin tones", "Lightweight", "Realistic feel", "Harness-compatible", "Skin-safe blend"],
    gradient: "from-blue-200 via-pink-100 to-white",
  },
  {
    id: "19",
    name: "Pulse Prostate Massager",
    slug: "pulse-prostate-massager",
    category: "men",
    tags: ["men", "prostate", "anal"],
    price: 62.99,
    originalPrice: 79.99,
    isSale: true,
    isNew: false,
    isBestseller: false,
    rating: 4.7,
    reviewCount: 143,
    description:
      "Remote-controlled prostate massager with perineum arm. 12 patterns, whisper-quiet, waterproof.",
    features: ["Remote control", "Perineum arm", "12 patterns", "Waterproof IPX6", "USB-C charging"],
    gradient: "from-violet-700 to-indigo-800",
  },
  {
    id: "20",
    name: "Kegel Ball Set",
    slug: "kegel-ball-set",
    category: "women",
    tags: ["women", "kegel", "wellness"],
    price: 36.99,
    isSale: false,
    isNew: false,
    isBestseller: false,
    rating: 4.6,
    reviewCount: 211,
    description:
      "Graduated kegel exercise balls for pelvic floor strengthening. Silicone coated, easy-retrieval cord.",
    features: ["3 weight options", "Silicone coated", "Retrieval cord", "Discreet design", "Beginner-friendly"],
    gradient: "from-rose-100 to-pink-200",
  },
  {
    id: "21",
    name: "Feather Tickler & Crop",
    slug: "feather-tickler-crop",
    category: "couples",
    tags: ["couples", "sensory", "bondage"],
    price: 28.99,
    originalPrice: 35.99,
    isSale: true,
    isNew: false,
    isBestseller: false,
    rating: 4.4,
    reviewCount: 88,
    description:
      "Elegant feather tickler with a mini crop on the reverse. Vegan-friendly materials, gift-ready.",
    features: ["2-in-1 design", "Vegan feather", "Gift box", "Beginner BDSM", "Easy grip handle"],
    gradient: "from-pink-200 to-red-200",
  },
  {
    id: "22",
    name: "Water-Based Lube — 100ml",
    slug: "water-based-lube-100ml",
    category: "couples",
    tags: ["lube", "couples", "essential"],
    price: 11.99,
    isSale: false,
    isNew: false,
    isBestseller: true,
    rating: 4.7,
    reviewCount: 734,
    description:
      "Silicone-toy-safe water-based lubricant. Condom-compatible, natural feel, easy wash-off.",
    features: ["Toy-safe", "Condom-compatible", "Natural feel", "Easy wash-off", "Fragrance-free"],
    gradient: "from-teal-100 to-cyan-200",
  },
  {
    id: "23",
    name: "Queer Erotica Anthology",
    slug: "queer-erotica-anthology",
    category: "lgbtq",
    tags: ["lgbtq", "book", "erotica"],
    price: 14.99,
    isSale: false,
    isNew: true,
    isBestseller: false,
    rating: 4.8,
    reviewCount: 56,
    description:
      "Curated short fiction celebrating queer pleasure, intimacy, and identity. Body-positive, joyful, and explicit.",
    features: ["240 pages", "Multiple authors", "All identities", "Body-positive", "Inclusive representation"],
    gradient: "from-purple-300 via-pink-200 to-yellow-200",
  },
  {
    id: "24",
    name: "Massage Candle — Vanilla",
    slug: "massage-candle-vanilla",
    category: "couples",
    tags: ["couples", "massage", "romance"],
    price: 22.99,
    isSale: false,
    isNew: false,
    isBestseller: false,
    rating: 4.6,
    reviewCount: 167,
    description:
      "Soy-based massage candle that melts into warm body oil. Vanilla & sandalwood scent, skin-safe at low temp.",
    features: ["Soy wax", "Skin-safe temp", "Massage oil", "Vanilla & sandalwood", "60 hour burn"],
    gradient: "from-amber-100 to-orange-200",
  },
];

export function getProductsByCategory(category: Category): Product[] {
  return products.filter((p) => p.category === category);
}

export function getSaleProducts(): Product[] {
  return products.filter((p) => p.isSale);
}

export function getBestsellers(): Product[] {
  return products.filter((p) => p.isBestseller);
}

export function getNewArrivals(): Product[] {
  return products.filter((p) => p.isNew);
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}
